import type { Product, Category } from "./types"

export const categories: Category[] = [
  { _id: "1", name: "Electronics", slug: "electronics", image: "/electronics-components.png" },
  { _id: "2", name: "Fashion", slug: "fashion", image: "/diverse-fashion-collection.png" },
  { _id: "3", name: "Home & Living", slug: "home", image: "/cozy-living-room.png" },
  { _id: "4", name: "Beauty", slug: "beauty", image: "/abstract-beauty.png" },
]

export const products: Product[] = [
  {
    _id: "1",
    name: "Premium Wireless Headphones",
    description: "High-quality audio with active noise cancellation",
    price: 299.99,
    image: "/wireless-headphones.png",
    images: ["/wireless-headphones.png"],
    category: "electronics",
    rating: 4.5,
    reviews: [],
    stock: 15,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "2",
    name: "Elegant Leather Watch",
    description: "Swiss-inspired timepiece with premium leather band",
    price: 199.99,
    image: "/leather-watch.png",
    images: ["/leather-watch.png"],
    category: "fashion",
    rating: 4.8,
    reviews: [],
    stock: 22,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "3",
    name: "Minimal Table Lamp",
    description: "Modern LED lamp with adjustable brightness",
    price: 89.99,
    image: "/modern-lamp.jpg",
    images: ["/modern-lamp.jpg"],
    category: "home",
    rating: 4.3,
    reviews: [],
    stock: 30,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "4",
    name: "Luxury Face Serum",
    description: "Anti-aging serum with natural ingredients",
    price: 129.99,
    image: "/face-serum.jpg",
    images: ["/face-serum.jpg"],
    category: "beauty",
    rating: 4.6,
    reviews: [],
    stock: 50,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "5",
    name: "Designer Sunglasses",
    description: "UV-protective lenses with premium frame",
    price: 249.99,
    image: "/stylish-sunglasses.png",
    images: ["/stylish-sunglasses.png"],
    category: "fashion",
    rating: 4.7,
    reviews: [],
    stock: 18,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "6",
    name: "Smart Home Hub",
    description: "Control all your smart devices from one place",
    price: 179.99,
    image: "/smart-home-device.png",
    images: ["/smart-home-device.png"],
    category: "electronics",
    rating: 4.4,
    reviews: [],
    stock: 25,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
